-- Estructura (sin datos) de las tablas de Contratos que usa el puente, tomada del esquema real de producción (2026-10-07).
-- Solo para la base de PRUEBA local (test/mysql/docker-compose.yml). fc_empresas va reducida a las columnas que el puente lee:
-- la tabla real guarda además usuario y clave de conexión y el puente nunca las consulta.
SET NAMES latin1;

-- Donde escribe el puente hoy (base viva de Contratos, leída el 2026-10-09). Los largos de rsocial, user_add, pc_add, user_mod
-- y pc_mod no se vieron completos en la base viva: aquí se suponen; el puente lee los reales al arrancar.
CREATE TABLE `fc_ofertas_adjudicadas` (
  `id` int(18) NOT NULL AUTO_INCREMENT,
  `empresa` char(6) DEFAULT NULL,
  `undnegocio` char(9) DEFAULT NULL,
  `num_oferta` int(10) DEFAULT '0',
  `nit` varchar(20) DEFAULT NULL,
  `rsocial` varchar(100) DEFAULT NULL,
  `vlr_adjudicado` int(18) DEFAULT '0',
  `vlr_manoobra` int(18) DEFAULT '0',
  `vlr_insumos` int(18) DEFAULT '0',
  `vlr_maquinaria` int(18) DEFAULT '0',
  `vlr_impuestos` int(18) DEFAULT '0',
  `vlr_otros` int(10) DEFAULT '0',
  `vlr_nocontinuos` int(18) DEFAULT '0',
  `user_add` varchar(12) DEFAULT NULL,
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_add` varchar(60) DEFAULT NULL,
  `user_mod` varchar(12) DEFAULT NULL,
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_mod` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Ofertas Adjudicadas';

CREATE TABLE `fc_contratos_tarifa_inicial` (
  `id` int(18) NOT NULL AUTO_INCREMENT,
  `empresa` char(6) DEFAULT '',
  `undnegocio` char(9) DEFAULT '',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `nit` varchar(20) DEFAULT '',
  `rsocial` varchar(100) DEFAULT '',
  `ncontrato` varchar(20) DEFAULT '',
  `aiu` decimal(13,10) DEFAULT NULL,
  `otrbasesn2` int(1) DEFAULT '0',
  `marco` int(1) DEFAULT '0',
  `tfa_global` decimal(1,0) DEFAULT '0',
  `consec` int(5) DEFAULT '0',
  `codservicio` char(3) DEFAULT '',
  `descripcion` varchar(254) DEFAULT '',
  `personas` int(10) DEFAULT '0',
  `tipo` char(3) DEFAULT '',
  `tipo_adm` char(1) DEFAULT '',
  `tarifa` decimal(18,0) DEFAULT '0',
  `tar_manoobra` decimal(18,0) DEFAULT '0',
  `tar_insumos` decimal(18,0) DEFAULT '0',
  `tar_maquinaria` decimal(18,0) DEFAULT '0',
  `tar_impuestos` decimal(18,0) DEFAULT '0',
  `tar_otros` int(10) DEFAULT '0',
  `tar_nocontinuos` decimal(18,2) DEFAULT '0.00',
  `codmun` varchar(15) DEFAULT '',
  `user_add` varchar(12) DEFAULT '',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_add` varchar(60) DEFAULT NULL,
  `user_mod` varchar(12) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_mod` varchar(60) DEFAULT NULL,
  `dias_tarifa` int(2) DEFAULT '30',
  `hay_cargos_recorrido` int(1) DEFAULT '0',
  `nro_factura` decimal(10,0) DEFAULT '0',
  `sector_economico` char(20) DEFAULT '',
  `id_oferta_adjudicada` int(18) DEFAULT '0',
  `control_st` int(1) DEFAULT '0',
  `por_estampilla` decimal(10,4) DEFAULT '0.0000',
  `solo_hras_extras` int(1) DEFAULT '0',
  `tar_examenes` decimal(18,0) DEFAULT '0',
  `tar_dotacion` decimal(18,0) DEFAULT '0',
  `exa_medico_vta` int(1) DEFAULT '0',
  `venta_dotacion` int(1) DEFAULT '0',
  `dot_epp_factur` int(1) DEFAULT '0',
  `costos_reembol` int(1) DEFAULT '0',
  `aplica_dotacion` int(1) NOT NULL DEFAULT '0',
  `aplica_examen` int(1) NOT NULL DEFAULT '0',
  `aiu_examenes` decimal(5,2) DEFAULT '0.00',
  `aiu_dotacion` decimal(5,2) DEFAULT '0.00',
  `moneda` varchar(3) DEFAULT 'COP',
  `origen_proceso` varchar(3) DEFAULT NULL COMMENT 'LIC=Licitacion Publica, INV=Invitacion Privada',
  `aplica_curso` int(1) NOT NULL DEFAULT '0',
  `curso_vta` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='TARIFA Inicial Comercial del Contrato';

CREATE TABLE `fc_contratos_cargos_iniciales` (
  `id` int(18) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `ncontrato` char(20) DEFAULT '',
  `consec` decimal(10,0) DEFAULT '0',
  `concepto` char(3) DEFAULT '',
  `cod_seccion` decimal(4,0) DEFAULT '0',
  `punto_entrega` char(11) DEFAULT '',
  `tipo_cargo` char(3) DEFAULT '',
  `item` decimal(5,0) DEFAULT '0',
  `cargo` decimal(5,0) DEFAULT '0',
  `jornada` decimal(5,2) DEFAULT '0.00',
  `horassem` decimal(5,0) DEFAULT '0',
  `cod_sede` decimal(5,0) DEFAULT '0',
  `cantidad` decimal(5,0) DEFAULT '0',
  `vlr_unitario` decimal(15,5) DEFAULT '0.00000',
  `vlr_total` decimal(18,5) DEFAULT '0.00000',
  `vlr_cargos` int(12) DEFAULT '0',
  `vlr_insumos` int(12) DEFAULT '0',
  `vlr_equipos` int(12) DEFAULT '0',
  `vlr_costos_adm` int(12) DEFAULT '0',
  `vlr_otros` int(12) DEFAULT '0',
  `vlr_no_conts` int(12) DEFAULT '0',
  `vlr_serv_oper` int(12) DEFAULT '0',
  `vlr_dcto_oper` int(12) DEFAULT '0',
  `vlr_servicio_operario` int(12) DEFAULT '0',
  `vlr_descto_operario` int(12) DEFAULT '0',
  `autorizado` decimal(1,0) DEFAULT '0',
  `codmun` char(5) DEFAULT '',
  `salario` decimal(10,0) DEFAULT '0',
  `modo` decimal(1,0) DEFAULT '0',
  `dotm` char(4) DEFAULT '',
  `vlr_dotm` decimal(12,2) DEFAULT '0.00',
  `dotf` char(4) DEFAULT '',
  `vlr_dotf` decimal(12,2) DEFAULT '0.00',
  `riesgo` decimal(1,0) DEFAULT '0',
  `cod_frecuencia` int(3) DEFAULT '0',
  `nro_veces_mes` int(2) DEFAULT '0',
  `vlr_frec_serv` int(12) DEFAULT '0',
  `codhorario` char(5) DEFAULT '',
  `horario` varchar(254) DEFAULT '',
  `tipocont` char(3) DEFAULT '',
  `epp` char(5) DEFAULT '',
  `examen` char(5) DEFAULT '',
  `clasebono` char(2) DEFAULT '',
  `tipobono` char(2) DEFAULT '',
  `vrbonoliq` decimal(14,0) DEFAULT '0',
  `snextras` decimal(1,0) DEFAULT '0',
  `cnextras` decimal(5,0) DEFAULT '0',
  `snrecargos` decimal(1,0) DEFAULT '0',
  `cnrecargos` decimal(5,0) DEFAULT '0',
  `snfestivos` decimal(1,0) DEFAULT '0',
  `cnfestivos` decimal(5,0) DEFAULT '0',
  `snextrasf` decimal(1,0) DEFAULT '0',
  `cnextrasf` decimal(5,0) DEFAULT '0',
  `rnocturno` decimal(10,0) DEFAULT '0',
  `ediurnas` decimal(10,0) DEFAULT '0',
  `rfestivas` decimal(10,0) DEFAULT '0',
  `enocturnas` decimal(10,0) DEFAULT '0',
  `hfestivas` decimal(10,0) DEFAULT '0',
  `efestivas` decimal(10,0) DEFAULT '0',
  `enocturnasf` decimal(10,0) DEFAULT '0',
  `vtarifavig` decimal(14,0) DEFAULT '0',
  `snarmas` decimal(1,0) DEFAULT '0',
  `sector_vigi` char(1) DEFAULT '',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `user_add` char(12) DEFAULT '',
  `pc_add` varchar(40) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `user_mod` char(12) DEFAULT '',
  `sn_recorrido` int(1) DEFAULT '0',
  `clasebono_alim` char(2) DEFAULT '',
  `vrbonoliq_alim` int(10) DEFAULT '0',
  `clasebono_trans` char(2) DEFAULT '',
  `vrbonoliq_trans` int(10) DEFAULT '0',
  `clasebono_prod` char(2) DEFAULT '',
  `vrbonoliq_prod` int(10) DEFAULT '0',
  `clasebono_prest` char(2) DEFAULT '',
  `vrbonoliq_prest` int(10) DEFAULT '0',
  `cantbono_oca` int(6) DEFAULT '0',
  `vrbonoliq_oca` int(10) DEFAULT '0',
  `cicloaplic_oca` char(7) DEFAULT '',
  `cod_grupo_curso` char(5) DEFAULT '',
  `vr_bono_rotativo` int(10) DEFAULT '0',
  `tp_bono_rotativo` varchar(10) DEFAULT '0',
  `vlr_unitario_va` decimal(15,5) DEFAULT '0.00000',
  `vlr_total_va` decimal(18,5) DEFAULT '0.00000',
  `clase` int(1) DEFAULT '1',
  `nom_cargo` varchar(100) NOT NULL DEFAULT '',
  `nivel_educacion` varchar(50) NOT NULL DEFAULT '',
  `titulo_educacion` varchar(100) NOT NULL DEFAULT '',
  `curso_formacion` varchar(100) NOT NULL DEFAULT '',
  `experiencia` int(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Mano de Obra Inicial de Comercial';

CREATE TABLE `fc_contratos_equipos_iniciales` (
  `id` int(18) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `ncontrato` char(20) DEFAULT '',
  `consec` decimal(5,0) DEFAULT '0',
  `concepto` char(3) DEFAULT '',
  `tipo_servicio` char(3) DEFAULT '',
  `codmun` char(5) DEFAULT '',
  `punto_entrega` char(11) DEFAULT '',
  `nom_punto_entrega` char(50) DEFAULT '',
  `tipo_equipo` char(3) DEFAULT '',
  `subtipo_equipo` char(3) DEFAULT '',
  `codigo` char(10) DEFAULT '',
  `descrip_equipo` varchar(50) DEFAULT '',
  `precio_costo` decimal(18,2) DEFAULT '0.00',
  `porc_vlr_compra` decimal(3,2) DEFAULT '0.00',
  `cantidad` decimal(10,2) DEFAULT '0.00',
  `frecuencia` decimal(3,0) DEFAULT '0',
  `valor` decimal(18,5) DEFAULT '0.00000',
  `cant_facturar` decimal(10,2) DEFAULT '0.00',
  `valor_inicial` decimal(18,2) DEFAULT '0.00',
  `user_add` varchar(12) DEFAULT '',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_add` varchar(60) DEFAULT NULL,
  `user_mod` varchar(12) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_mod` varchar(60) DEFAULT NULL,
  `dtipo_equipo` char(3) DEFAULT '',
  `vlr_mes_mantenimiento` int(15) DEFAULT '0',
  `vlr_mes_otr_rubros` int(15) DEFAULT '0',
  `clase` int(1) DEFAULT '1',
  `valor_inicial_va` decimal(15,5) DEFAULT '0.00000',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='MAQUINAS Iniciales Comercial del Contrato';

CREATE TABLE `fc_contratos_costos_admtivos_iniciales` (
  `id` int(18) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `ncontrato` char(20) DEFAULT '',
  `consec` decimal(5,0) DEFAULT '0',
  `concepto` char(3) DEFAULT '',
  `punto_entrega` char(11) DEFAULT '',
  `nombre_punto` char(60) DEFAULT '',
  `codmun` char(5) DEFAULT '',
  `id_cpto_costo` decimal(18,0) DEFAULT '0',
  `valor` decimal(18,0) DEFAULT '0',
  `user_add` varchar(12) DEFAULT '',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_add` varchar(60) DEFAULT '',
  `user_mod` varchar(12) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_mod` varchar(60) DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Costos Administrativos de la Oferta';

CREATE TABLE `fc_contratos_no_continuos_iniciales` (
  `id` int(18) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `ncontrato` char(20) DEFAULT '',
  `consec` decimal(5,0) DEFAULT '0',
  `concepto` char(3) DEFAULT '',
  `cod_seccion` int(4) DEFAULT '0',
  `UEN_Adm` char(3) DEFAULT '',
  `cod_sede` decimal(5,0) DEFAULT '0',
  `actividad` int(3) DEFAULT '0',
  `tipo_actividad` char(5) DEFAULT '',
  `tipo` int(1) DEFAULT '0',
  `clase` int(1) DEFAULT '0',
  `frecuencia` int(3) DEFAULT '0',
  `cant_frecuencia` decimal(50,0) DEFAULT '0',
  `cant_dias` decimal(50,0) DEFAULT '0',
  `punto_entrega` char(11) DEFAULT '',
  `nombre_punto` char(60) DEFAULT '',
  `codmun` char(5) DEFAULT '',
  `item_descrip` decimal(18,0) DEFAULT '0',
  `descrip_servicio` varchar(250) DEFAULT '',
  `tipo_facturacion` char(3) DEFAULT '',
  `valor` decimal(18,0) DEFAULT '0',
  `vlr_mes` int(12) DEFAULT '0',
  `vlr_mano_obra` decimal(18,0) DEFAULT '0',
  `vlr_insumos` decimal(18,0) DEFAULT '0',
  `vlr_equipos` decimal(18,0) DEFAULT '0',
  `vlr_costos` int(12) DEFAULT '0',
  `vlr_max_serv_sub` int(12) DEFAULT '0',
  `cant_servs_mes` int(10) DEFAULT '0',
  `cant_servs_contrato` int(10) DEFAULT '0',
  `cant_max_dias_servicio` int(10) DEFAULT '0',
  `cant_max_hrs_servicio` int(10) DEFAULT '0',
  `dias_habiles` int(10) DEFAULT '0',
  `dias_festivos` int(10) DEFAULT '0',
  `habil_diurnas` int(10) DEFAULT '0',
  `festi_diurnas` int(10) DEFAULT '0',
  `habil_nocturnas` int(10) DEFAULT '0',
  `festi_nocturnas` int(10) DEFAULT '0',
  `rnocturno` int(10) DEFAULT '0',
  `ediurnas` int(10) DEFAULT '0',
  `rfestivas` int(10) DEFAULT '0',
  `enocturnas` int(10) DEFAULT '0',
  `hfestivas` int(10) DEFAULT '0',
  `efestivas` int(10) DEFAULT '0',
  `enocturnasf` int(10) DEFAULT '0',
  `horas_jornada` decimal(10,7) DEFAULT '0.0000000',
  `rhumano` char(254) DEFAULT '',
  `oper_fijos` decimal(50,0) DEFAULT '0',
  `oper_adic` decimal(50,0) DEFAULT '0',
  `codhorario` char(5) DEFAULT '',
  `uen_punto` char(3) DEFAULT '',
  `maquinaria` char(254) DEFAULT '',
  `viaticos` int(20) DEFAULT '0',
  `serv_subcontratado` int(20) DEFAULT '0',
  `nit_proveedor` varchar(20) DEFAULT '',
  `ciudad` char(5) DEFAULT '',
  `user_add` varchar(12) DEFAULT '',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_add` varchar(60) DEFAULT '',
  `user_mod` varchar(12) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `pc_mod` varchar(60) DEFAULT '',
  `valor_va` decimal(15,5) DEFAULT '0.00000',
  `vlr_mes_va` decimal(15,5) DEFAULT '0.00000',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Servs. NO Continuos de la Oferta';

CREATE TABLE `fc_contratos_vlrs_agregs_iniciales` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `ncontrato` char(20) DEFAULT '',
  `consec` int(5) DEFAULT '0',
  `concepto` char(3) DEFAULT '',
  `tipo` int(1) DEFAULT '1',
  `valor` decimal(15,2) DEFAULT '0.00',
  `tipo_reinv` int(1) DEFAULT '1',
  `frec_reinv` int(3) DEFAULT '1',
  `porc_reinv` decimal(7,4) DEFAULT '0.0000',
  `fproc` datetime DEFAULT '0000-00-00 00:00:00',
  `usuario` varchar(50) DEFAULT '',
  `pc` varchar(50) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `empresa` (`empresa`),
  KEY `undnegocio` (`undnegocio`),
  KEY `num_oferta` (`num_oferta`),
  KEY `consec` (`consec`),
  KEY `concepto` (`concepto`),
  KEY `tipo` (`tipo`),
  KEY `tipo_reinv` (`tipo_reinv`),
  KEY `llave_1` (`empresa`,`undnegocio`,`num_oferta`,`consec`,`concepto`,`tipo`),
  KEY `llave_2` (`empresa`,`undnegocio`,`num_oferta`,`consec`,`concepto`),
  KEY `llave_3` (`empresa`,`undnegocio`,`num_oferta`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Almacena Valores Agregados de la Oferta.';

CREATE TABLE `fc_elemxcont` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `nit` varchar(20) DEFAULT '',
  `ncontrato` char(20) DEFAULT '',
  `tipo_insumo` char(3) DEFAULT '',
  `codele` char(10) DEFAULT '',
  `cantidad` double DEFAULT '0',
  `frecuencia` double DEFAULT '0',
  `vlr_unitario` double DEFAULT '0',
  `cantsoli` decimal(15,5) DEFAULT '0.00000',
  `num_oferta` decimal(10,0) DEFAULT '0',
  `consec` decimal(10,0) DEFAULT '0',
  `concepto` char(3) DEFAULT '',
  `codmun` char(5) DEFAULT '',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `user_add` char(12) DEFAULT '',
  `pc_add` varchar(40) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `user_mod` char(12) DEFAULT '',
  `nitloc` char(11) DEFAULT '',
  `nombre_punto` varchar(60) DEFAULT '',
  `clase` int(1) DEFAULT '1',
  `vlr_unitario_va` decimal(15,5) DEFAULT '0.00000',
  PRIMARY KEY (`id`),
  KEY `ncontrato` (`ncontrato`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `fc_preciosventas_oferta` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `undnegocio` char(3) DEFAULT '',
  `num_oferta` int(10) DEFAULT '0',
  `ncontrato` varchar(20) DEFAULT '',
  `cliente` char(11) DEFAULT '',
  `nom_punto` varchar(60) DEFAULT '',
  `codigo` char(10) DEFAULT '',
  `valor` decimal(15,4) DEFAULT '0.0000',
  `valor_anterior` decimal(15,4) DEFAULT '0.0000',
  `aiu` decimal(8,4) DEFAULT '0.0000',
  `fadd` datetime DEFAULT '0000-00-00 00:00:00',
  `user_add` char(12) DEFAULT '',
  `fmod` datetime DEFAULT '0000-00-00 00:00:00',
  `user_mod` char(12) DEFAULT '',
  `pc_mod` char(60) DEFAULT '',
  `vr_costo` decimal(15,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Listas de Precio en la Oferta';

CREATE TABLE `fc_clientes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `undnegocio` char(3) DEFAULT '',
  `nit` varchar(20) NOT NULL DEFAULT '',
  `sucursal` char(2) NOT NULL DEFAULT '00',
  `rsocial` varchar(100) NOT NULL DEFAULT '',
  `direccion` varchar(60) NOT NULL DEFAULT '',
  `ciudad` varchar(30) NOT NULL DEFAULT '',
  `telefono` varchar(20) NOT NULL DEFAULT '',
  `codmun` varchar(5) DEFAULT '',
  `regimen` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ciiu` char(4) DEFAULT '',
  `ccostos` int(10) unsigned NOT NULL DEFAULT '0',
  `email` varchar(100) NOT NULL DEFAULT '',
  `gerente` varchar(40) NOT NULL DEFAULT '',
  `aiu` double NOT NULL DEFAULT '0',
  `sniva` char(1) NOT NULL DEFAULT '',
  `reteiva` char(1) NOT NULL DEFAULT '',
  `retefte` char(1) NOT NULL DEFAULT '',
  `snbasertf` char(1) NOT NULL,
  `reteica` char(1) NOT NULL DEFAULT '',
  `tarifa_ica` decimal(15,4) DEFAULT '0.0000',
  `tipo` char(2) NOT NULL DEFAULT '00',
  `tipocli` int(1) DEFAULT '0',
  `es_tributario` decimal(1,0) DEFAULT '0',
  `codigoiva` char(3) NOT NULL DEFAULT '000',
  `diasplazo` int(3) unsigned NOT NULL DEFAULT '0',
  `comprobante` int(6) NOT NULL DEFAULT '0',
  `snactivo` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `snfactfija` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `cant_fact` int(3) DEFAULT '1',
  `diasfactura` int(3) unsigned NOT NULL DEFAULT '0',
  `diasfactura2` int(2) NOT NULL DEFAULT '0',
  `diaradicacion` int(2) DEFAULT '0',
  `ciudadradicacion` char(40) DEFAULT '',
  `proc_factura` tinyint(1) DEFAULT '1',
  `snesporadico` char(1) NOT NULL DEFAULT '',
  `valor` int(10) DEFAULT '0',
  `act_Eco` char(5) DEFAULT '',
  `contacto_f` varchar(40) DEFAULT '',
  `email_f` varchar(100) DEFAULT '',
  `email_c` varchar(100) DEFAULT ' ',
  `telefono_f` varchar(20) DEFAULT '',
  `docs_f` text,
  `snica` tinyint(1) DEFAULT '0',
  `snavisos` tinyint(1) DEFAULT '0',
  `snbomberil` tinyint(1) DEFAULT '0',
  `useradd` varchar(12) DEFAULT '',
  `fechaadd` datetime DEFAULT '0000-00-00 00:00:00',
  `usermod` varchar(12) DEFAULT '',
  `fechamod` datetime DEFAULT '0000-00-00 00:00:00',
  `fac_mesven` char(1) DEFAULT '',
  `fac_extemp` char(1) DEFAULT '',
  `otrbasesn` int(11) DEFAULT '0',
  `forma_pago_cliente` tinyint(1) DEFAULT NULL,
  `cod_financiera_cliente` varchar(2) DEFAULT NULL,
  `contacto_recaudo` varchar(40) DEFAULT NULL,
  `telefono_recaudo` varchar(20) DEFAULT '',
  `diasfactura_temp` int(3) DEFAULT '0',
  `diaradicacion_temp` int(2) DEFAULT '0',
  `tipo_doc` decimal(3,0) DEFAULT '0',
  `tipo_persona` decimal(3,0) DEFAULT '0',
  `primer_apellido` varchar(25) DEFAULT '',
  `segundo_apellido` varchar(25) DEFAULT '',
  `primer_nombre` varchar(25) DEFAULT '',
  `segundo_nombre` varchar(25) DEFAULT '',
  `tipo_radica` int(1) DEFAULT '0',
  `tipo_org_juridica_Adq` varchar(1) DEFAULT '',
  `agencyid_admin_Adq` varchar(3) DEFAULT '',
  `agencyname_admin_Adq` varchar(60) DEFAULT '',
  `digito_verifica_Adq` varchar(1) DEFAULT '',
  `tipodoc_ident_Adq` int(3) DEFAULT '0',
  `respon_fiscal_Adq` varchar(80) DEFAULT '',
  `regimen_fiscal_Adq` varchar(2) DEFAULT '',
  `codmun_dir_fiscal_Adq` varchar(5) DEFAULT '',
  `postalzone_dir_fiscal_Adq` varchar(20) DEFAULT '',
  `coddpto_dir_fiscal_Adq` varchar(2) DEFAULT '',
  `dir_fiscal_libre_Adq` varchar(90) DEFAULT '',
  `codpais_dir_fiscal_Adq` varchar(20) DEFAULT '',
  `languageid_pais_fiscal_Adq` varchar(10) DEFAULT '',
  `id_tributo_Adq` varchar(20) DEFAULT '',
  `agencyid_admin_Adq_FAK45` varchar(3) DEFAULT '',
  `agencyname_admin_Adq_FAK46` varchar(60) DEFAULT '',
  `digito_verifica_Adq_FAK47` varchar(1) DEFAULT '',
  `tipodoc_identidad_Adq` int(3) DEFAULT '0',
  `postalzone_dir_Adq` varchar(20) DEFAULT '',
  `info_libre_dir_Adq` varchar(90) DEFAULT '',
  `codpais_dir_Adq` varchar(20) DEFAULT '',
  `languageid_pais_Adq` varchar(10) DEFAULT '',
  `medio_pago_Adq` varchar(10) DEFAULT '',
  `TipoDocumento` char(2) DEFAULT '',
  `Apellido1` char(30) DEFAULT '',
  `Apellido2` char(30) DEFAULT '',
  `Nombre1` char(30) DEFAULT '',
  `Nombre2` char(30) DEFAULT '',
  `controlar_costos` int(1) DEFAULT '0',
  `cedula_rl` varchar(20) DEFAULT '',
  `representante_legal` varchar(50) DEFAULT '',
  `lugar_expedicion_rl` varchar(30) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `nit` (`nit`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Clientes en Contratacion';

CREATE TABLE `gl_undnegocios` (
  `codigo` char(3) DEFAULT '',
  `nombre` char(40) DEFAULT '',
  `codigonom` char(2) DEFAULT '',
  `dbnomina` char(40) NOT NULL DEFAULT '',
  `ccostos` int(3) unsigned DEFAULT '0',
  `codmun` char(5) DEFAULT '',
  `codigoalm` char(11) DEFAULT '',
  `tipo` char(1) DEFAULT '',
  `empresa` char(2) DEFAULT '00',
  `bodega_ser` char(3) DEFAULT '',
  `parametro_db` char(60) DEFAULT '',
  `db` char(60) DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Unidades de Negocio';

CREATE TABLE `fc_empresas` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `codigo` char(2) DEFAULT '0',
  `undnegocio` char(3) NOT NULL DEFAULT '',
  `rsocial` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `fc_conceptos` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT '',
  `codcpto` char(3) DEFAULT '000',
  `codigo` char(3) DEFAULT '',
  `descrip` char(60) DEFAULT '',
  `nombre` char(40) DEFAULT '',
  `cuenta` char(10) DEFAULT '',
  `nza` int(1) unsigned DEFAULT '0',
  `porc` double(15,5) DEFAULT '0.00000',
  `base` char(6) DEFAULT '',
  `tcpto` char(2) DEFAULT '00',
  `iva` char(3) DEFAULT '000',
  `rtiva` char(3) DEFAULT '000',
  `rtfte` char(3) DEFAULT '000',
  `rtica` char(3) DEFAULT '000',
  `grav` int(1) unsigned DEFAULT '0',
  `liqaiu` tinyint(1) unsigned DEFAULT '0',
  `tasa` double(10,2) DEFAULT '0.00',
  `caiu` char(3) DEFAULT '000',
  `snccos` char(1) DEFAULT '',
  `cod_municipio` char(5) DEFAULT '',
  `venta` int(1) DEFAULT '0',
  `ciiu` char(5) DEFAULT '',
  `nominasn` int(11) DEFAULT '0',
  `cuenngrav` char(10) DEFAULT '',
  `sncartera` int(1) DEFAULT '0',
  `vlrbasertf` int(10) DEFAULT '0',
  `imprime_en_face` int(1) DEFAULT '0',
  `descrip_al_facturar` varchar(250) DEFAULT '',
  `verificar_turnos` int(10) DEFAULT '0',
  `tipo_facturacion` char(3) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `codcpto` (`codcpto`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='tabla de conceptos de facturacion';

-- fc_control va reducida a lo que el puente usa: la real tiene 157 columnas, entre ellas usuario y clave de conexión.
-- Una fila por (empresa, UEN); num_oferta guarda el ÚLTIMO número de oferta usado.
CREATE TABLE `fc_control` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `empresa` char(2) DEFAULT '',
  `undnegocio` char(3) DEFAULT NULL,
  `num_oferta` decimal(10,0) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- fc_horarios va reducida a lo que el puente consulta (la real tiene 120 columnas, todas de cálculo de horas); utf8 como la real.
CREATE TABLE `fc_horarios` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `codigo` char(5) DEFAULT NULL,
  `horario` char(200) DEFAULT '',
  `snactivo` int(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `codigo` (`codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
